# This file is for Cloudflare Pages configuration
name = "finance-cpn"

[env.production]
vars = { VITE_LIFF_ID = "2007620942-1qMRZYMP", VITE_API_BASE = "https://military-finance.onrender.com/api" }

[env.preview]
vars = { VITE_LIFF_ID = "2007620942-1qMRZYMP", VITE_API_BASE = "https://military-finance.onrender.com/api" }
